### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by AMyriad** [AMyriad/Obsidian#4]
Because I love getting sidetracked, here I'll outline what's needed to get the project finished. Things will be ordered by importance, going from rules and info crucial to play the game to things and mechanics that will help flesh out both the world and the game.

### Character Creation
- [ ] Character creation guide page -{ Steps needed to make a character
- [ ] Origins -{ Lore info, benefits, and age
- [ ] Character details -{ Background, drive, fear, usual looks, and past allegiance
- [ ] Starting equipment -{ Inventory rules (carry cap), kits, starting bonuses, personal trinket
- [ ] Hub creation page (a single page is probably enough) -{ Hub type, power source, hub background. and hub quirk

### Mechanics
- [ ] Life and death -{ HP, DR, critical states, 
- [ ] Survival -{ Explaining steps, food, water, sleep, oxygen, and heat
- [ ] Abilities -{ Ability checks, opposed rolls, advantage/disadvantage, main ability, and ability explanations (god)
- [ ] Guns -{ Gun stat explanations
- [ ] Combat -{ Action points, initiative, cover, and list of actions (god)
- [ ] Spacecraft -{ Space travel, and confrontations
- [ ] Construction/Condition -{ Condition, components and vehicle parts, repairing, dismantling, crafting

## Extra Things
- [ ] Introduction (do this first)
- [ ] Drugs
- [ ] Spacecraft modules
- [ ] More corporations lore
- [ ] Tenebris system planets
- [ ] Cybernetics
- [ ] Hacking
- [ ] Surgery
- [ ] Gunsmithing
- [ ] Botany
